### ISSUE TITLE
Could you please create npm installable package for this project?

### ISSUE THREAD

**Issue by attila123** [twaldecker/typings-base64#1]
Hi,
I guess nowadays npm is the most popular js package manager.
It would be so dreamy if this project could be simply installed with npm. :)

**Comment by twaldecker** [comment]
Can you provide a pull-request with a package.json.

Then you can install with npm from github directly.

**Comment by attila123** [comment]
Sorry, I confused this with `@types`. In fact `@types` are better, because they simply install with npm, no additional steps are needed. I just see that `@types/base-64` is available (see https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/base-64 ), and can be installed simply as
```
npm i @types/base-64 --save-dev
```
So this issue can be closed, thanks.
